In [3]:
import pandas as pd

carebeds = pd.read_csv('https://raw.githubusercontent.com/arno-haas/python-project/master/IBAuslastung.csv')
carebeds.info()
carebeds.head(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 1 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   time;Belegung Intensivbetten in %;Timestamp  36 non-null     object
dtypes: object(1)
memory usage: 416.0+ bytes

   time;Belegung Intensivbetten in %;Timestamp
0            01.04.2020;21;2020-05-06T09:30:00
1            02.04.2020;23;2020-05-06T09:30:00
2            03.04.2020;26;2020-05-06T09:30:00
3            04.04.2020;25;2020-05-06T09:30:00
4            05.04.2020;24;2020-05-06T09:30:00
5            06.04.2020;24;2020-05-06T09:30:00
6            07.04.2020;21;2020-05-06T09:30:00
7            08.04.2020;21;2020-05-06T09:30:00
8            09.04.2020;21;2020-05-06T09:30:00
9            10.04.2020;21;2020-05-06T09:30:00
10           11.04.2020;22;2020-05-06T09:30:00
11           12.04.2020;22;2020-05-06T09:30:00
12           13.04.2020;19;2020-05-06T09:30:00
13           14.04.2020;20;2020-05-06T09:30:00
14           15.04.2020;20;2020-05-06T09:30:00
15           16.04.2020;21;2020-05-06T09:30:00
16           17.04.2020;19;2020-05-06T09:30:00
17           18.04.2020;18;2020-05-06T09:30:00
18           19.04.2020;16;2020-05-06T09:30:00
19           20.04.2020;17;2020-05-06T09:30:00